CREATE TABLE `price` (
  `actionid` char(1) DEFAULT NULL,
  `sku` varchar(12) NOT NULL DEFAULT '',
  `vendor_number` varchar(4) DEFAULT NULL,
  `manufacturer` varchar(35) DEFAULT NULL,
  `part_description1` varchar(35) DEFAULT NULL,
  `part_description2` varchar(35) DEFAULT NULL,
  `retail_price` decimal(10,2) DEFAULT NULL,
  `mfgpartno` varchar(20) DEFAULT NULL,
  `weight` varchar(9) DEFAULT NULL,
  `upc_code` varchar(13) DEFAULT NULL,
  `length` varchar(7) DEFAULT NULL,
  `width` varchar(7) DEFAULT NULL,
  `height` varchar(7) DEFAULT NULL,
  `price_change_flag` varchar(1) DEFAULT NULL,
  `customer_price` decimal(10,2) DEFAULT NULL,
  `special_price_flag` varchar(1) DEFAULT NULL,
  `availability_flag` varchar(1) DEFAULT NULL,
  `sku_status` varchar(1) DEFAULT NULL,
  `cpu_code` varchar(6) DEFAULT NULL,
  `media_type` varchar(4) DEFAULT NULL,
  `category` varchar(4) DEFAULT NULL,
  `item_receipt_flag` varchar(1) DEFAULT NULL,
  `instant_rebate_flag` varchar(1) DEFAULT NULL,
  `sub_part_number` varchar(12) DEFAULT NULL,
  `available_quantity` varchar(8) DEFAULT NULL,
  `price_category` varchar(1) DEFAULT NULL,
  `price_class` varchar(1) DEFAULT NULL,
  PRIMARY KEY (`sku`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

